### ISSUE TITLE
How to build in ros melodic Ubuntu 18.04

### ISSUE THREAD

**Issue by jamesheatonrdm** [EpsAvlc/rslidar_to_velodyne#2]
I am trying to build the package using catkin_make but I am getting all kinds of errors and there is hardly any documentation for this.
I am running ros melodic on Ubuntu 18.04 but whenever I try to catkin_make I get all kinds of errors such as at convert.cpp:46:21: error: 'velodyne_pointcloud' was not declared in this scope.

How do I fix these?

**Comment by yzzymt** [comment]
#include <velodyne_pointcloud/point_types.h>

**Comment by hjfenghj** [comment]
> #include <velodyne_pointcloud/point_types.h>

非常感谢

**Comment by sco09** [comment]
sudo apt install ros-melodic-velodyne-pointcloud
this package is needed

> #include <velodyne_pointcloud/point_types.h>
